# Generated by Django 4.2.14 on 2024-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_product_description_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=models.DecimalField(decimal_places=3, max_digits=10, null=True), upload_to='', width_field=models.DecimalField(decimal_places=3, max_digits=10, null=True)),
        ),
    ]
