# Generated by Django 4.2.14 on 2024-07-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_product_height_remove_product_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
