# Generated by Django 4.2.14 on 2024-07-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_height_product_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
